### ISSUE TITLE
Crash on C++ files

### ISSUE THREAD

**Issue by Sod-Almighty** [chfritz/atom-sane-indentation#13]
1. Open a C++ file (in my case, an .ino Arduino file)
2. Press enter on a line.
3. Crash

Atom 1.26.1 on Mac.
```
TypeError: Cannot read property 'reset' of null
    at TokenizedLine.module.exports.TokenizedLine.getTokenIterator (/Applications/Atom.app/Contents/Resources/app/src/tokenized-line.js:20:38)
    at TreeSitterLanguageMode.e.languageMode.suggestedIndentForBufferRow (/Users/infinity/.atom/packages/sane-indentation/lib/sane-indentation.js:211:43)
    at TextEditor.suggestedIndentForBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:4485:26)
    at TextEditor.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:4494:36)
    at Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:482:25)
    at result.mutateSelectedText.selection (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1350:37)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1387:92)
    at Array.map (native)
    at transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1387:66)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3249:53)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1361:23)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.editor:newline (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:641:27)
    at /Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:701:40
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at HTMLElement.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:700:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```
If I change filetype to something else, and then change it back to C++, it starts working again.

**Comment by chfritz** [comment]
hm, I can't reproduce it on Linux, but I did have to rebuild the package for the new atom version (1.26) -- was build against 1.24. However that is done by atom itself and it won't load the package until it was rebuild. Which version of this package are you using?

**Comment by Sod-Almighty** [comment]
I'm afraid I had to uninstall it for my own sanity, so I can't check. But I checked for updates first and it said there weren't any; so I assume it's the latest version.

**Comment by chfritz** [comment]
ok thanks, will try Mac also when I get a chance.

**Comment by chfritz** [comment]
I've now tried this on a Mac as well using the latest version of atom (1.27.0) and still wasn't able to reproduce this.
