### ISSUE TITLE
Uncaught TypeError: e.languageMode.getSyntaxNodeAtPosition is not a function

### ISSUE THREAD

**Issue by alvarongg** [chfritz/atom-sane-indentation#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.5
**Thrown From**: [sane-indentation](https://github.com/chfritz/atom-sane-indentation) package 1.1.2

### Stack Trace

Uncaught TypeError: e.languageMode.getSyntaxNodeAtPosition is not a function

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: e.languageMode.getSyntaxNodeAtPosition is not a function
    at getHighestSyntaxNodeAtPosition (/packages/sane-indentation/lib/sane-indentation.js:88:35)
    at TextMateLanguageMode.suggestedIndentForBufferRow (/packages/sane-indentation/lib/sane-indentation.js:110:24)
    at TextEditor.suggestedIndentForBufferRow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:58503)
    at TextEditor.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:58594)
    at TextEditor.autoIndentBufferRows (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:58723)
    at Selection.autoIndentSelectedRows (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:543238)
    at mutateSelectedText.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:43319)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492395)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39529)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.autoIndentSelectedRows (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:43295)
    at TextEditor.editor:auto-indent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:305986)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:307274
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492395)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at HTMLElement.s.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:307217)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349392)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347867)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718772)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:726695)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -2:35.4.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -2:35.4.0 snippets:next-tab-stop (input.hidden-input)
     -2:35.4.0 snippets:expand (input.hidden-input)
     -2:35.4.0 editor:indent (input.hidden-input)
  4x -2:30.8.0 core:save (input.hidden-input)
     -2:18.9.0 tree-view:move (span.name.icon.icon-file-text)
  4x -2:17.3.0 core:backspace (input.hidden-input)
     -2:15.2.0 core:save (input.hidden-input)
     -2:11.2.0 tree-view:move (span.name.icon.icon-file-text)
  8x -2:10.7.0 core:move-right (input.hidden-input)
  4x -2:09.5.0 core:backspace (input.hidden-input)
     -2:08.2.0 core:confirm (input.hidden-input)
  2x -2:07.2.0 core:save (input.hidden-input)
  6x -1:23.8.0 core:backspace (input.hidden-input)
     -0:15.1.0 sane-indentation:toggle (input.hidden-input)
     -0:02.6.0 editor:auto-indent (input.hidden-input)
```

### Non-Core Packages

```
emmet 2.4.3 
html-tag-auto-complete 0.1.1 
html-template-generator 0.3.0 
sane-indentation 1.1.2 
```

**Comment by chfritz** [comment]
Confirmed. This seems to be new with Atom 1.41, and I only see this in HTML mode so far. Will investigate.

**Comment by chfritz** [comment]
This is patched now, but not in a very nice way. A function disappeared from the languageMode in atom for HTML files (but only for some!?). it's very strange. But when this happens, sane-indentation will fall back to the normal indentation method, so at least the error won't happen anymore.
