### ISSUE TITLE
Installing “sane-indentation@0.0.7” failed.

### ISSUE THREAD

**Issue by nemchik** [chfritz/atom-sane-indentation#7]
> > oniguruma@5.1.2 install C:\Users\ENEMCH~1.KEE\AppData\Local\Temp\apm-install-dir-116514-97032-1k1cxnj\node_modules\sane-indentation\node_modules\oniguruma
> > node-gyp rebuild
> 
> C:\Users\ENEMCH~1.KEE\AppData\Local\Temp\apm-install-dir-116514-97032-1k1cxnj\node_modules\sane-indentation\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> 
> gypnpm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe" "C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\enemchik.KEEFORCE\.atom\.apm\.apmrc" "--userconfig" "C:\Users\enemchik.KEEFORCE\.atom\.apmrc" "install" "C:\Users\ENEMCH~1.KEE\AppData\Local\Temp\d-116514-97032-1vmtr35\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2010"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the oniguruma package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls oniguruma
> npm ERR! There is likely additional logging output above.
> I'm not sure what's happening here, but it seems I am unable to install this package.
> As you might have guessed by the output above, I am running Atom 1.8.0 on Windows 10.

**Comment by chfritz** [comment]
Old and not seen again.

**Comment by nemchik** [comment]
So... I still can't install this package on Atom 1.27.

Here is an updated log output
`Installing “sane-indentation@0.2.1” failed.Hide output…`
```
> oniguruma@6.2.1 install C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma
> node-gyp rebuild


C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\enemchik\AppData\Local\atom\app-1.27.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\enemchik\AppData\Local\atom\app-1.27.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
  regcomp.c
  regenc.c
  regerror.c
  regexec.c
..\deps\onig\regexec.c(1344): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1348): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1364): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1368): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1672): warning C4311: 'type cast': pointer truncation from 'OnigUChar *' to 'unsigned int' [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regcomp.c(563): warning C4311: 'type cast': pointer truncation from 'OnigUChar *' to 'unsigned int' [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1737): warning C4311: 'type cast': pointer truncation from 'OnigUChar *' to 'unsigned int' [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2082): warning C4311: 'type cast': pointer truncation from 'void *' to 'OnigStackIndex' [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2096): warning C4311: 'type cast': pointer truncation from 'void *' to 'OnigStackIndex' [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2113): warning C4311: 'type cast': pointer truncation from 'void *' to 'OnigStackIndex' [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2119): warning C4311: 'type cast': pointer truncation from 'void *' to 'OnigStackIndex' [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2153): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2157): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2185): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2189): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2217): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2221): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2256): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2260): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2372): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'OnigUChar *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2395): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'OnigUChar *' of greater size [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\oniguruma.vcxproj]
  regext.c
  reggnu.c
  regparse.c
  regposerr.c
  regposix.c
  regsyntax.c
  regtrav.c
  regversion.c
  st.c
  ascii.c
  big5.c
  cp1251.c
  euc_jp.c
  euc_kr.c
  euc_tw.c
  gb18030.c
  iso8859_1.c
  iso8859_2.c
  iso8859_3.c
  iso8859_4.c
  iso8859_5.c
  iso8859_6.c
  iso8859_7.c
  iso8859_8.c
  iso8859_9.c
  iso8859_10.c
  iso8859_11.c
  iso8859_13.c
  iso8859_14.c
  iso8859_15.c
  iso8859_16.c
  koi8.c
  koi8_r.c
  mktable.c
  sjis.c
  unicode.c
  utf16_be.c
  utf16_le.c
  utf32_be.c
  utf32_le.c
  utf8.c
  win_delay_load_hook.cc
  oniguruma.vcxproj -> C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\Release\\oniguruma.lib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\onig_scanner.vcxproj]
  onig-result.cc
  onig-reg-exp.cc
  onig-scanner.cc
  onig-scanner-worker.cc
..\src\onig-scanner-worker.cc(37): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\onig_scanner.vcxproj]
  C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call'
..\src\onig-scanner-worker.cc(43): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\onig_scanner.vcxproj]
  C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call'
  onig-searcher.cc
  onig-string.cc
  win_delay_load_hook.cc
C:\Users\enemchik\.atom\.node-gyp\.node-gyp\iojs-1.7.11\Release\iojs.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2704CE [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\onig_scanner.vcxproj]

gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\enemchik\AppData\Local\atom\app-1.27.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\enemchik\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\enemchik\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\package.json'
npm WARN apm-install-dir-118415-21104-8384gl.i9abz3q5mi No description
npm WARN apm-install-dir-118415-21104-8384gl.i9abz3q5mi No repository field.
npm WARN apm-install-dir-118415-21104-8384gl.i9abz3q5mi No README data
npm WARN apm-install-dir-118415-21104-8384gl.i9abz3q5mi No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\enemchik\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\enemchik\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\enemchik\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\enemchik\\.atom\\.apmrc" "install" "C:\\Users\\enemchik\\AppData\\Local\\Temp\\d-118415-21104-1thzn92.wrrzppsyvi\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\npm-debug.log
```

**Comment by chfritz** [comment]
Sorry, I don't have a windows computer to try this on, but to me the error looks like something is amiss in your build setup:
```
fatal error LNK1106: invalid file or disk full: cannot seek to 0x2704CE [C:\Users\enemchik\AppData\Local\Temp\apm-install-dir-118415-21104-8384gl.i9abz3q5mi\node_modules\sane-indentation\node_modules\oniguruma\build\onig_scanner.vcxproj]
```
I'm assuming your disk is *not* full, right?

**Comment by nemchik** [comment]
Absolutely not! lol, hopefully it's not trying to use 34 GB because that's all I have free.
